In [10]:
import numpy as np
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix2 = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])
result_matrix=np.add(matrix1, matrix2)
print(result_matrix)
                    



[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [14]:
import numpy as np
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix2 = np.array([[9,8,7],
                    [6,5,4],
                    [3,2,1]])
result=np.dot(matrix1, matrix2)
print(result)
                    



[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [46]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)


[12, 4, 3]
[7, 5, 8]


In [50]:
my_str="Hello this is me samiksha"
words= [word.lower() for word in my_str.split()]
words.sort()
print("the sorted words are:")
for word in words:
    print(word)

the sorted words are:
hello
is
me
samiksha
this


In [73]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)


Hello he said and went


<>:2: SyntaxWarning: invalid escape sequence '\,'
<>:2: SyntaxWarning: invalid escape sequence '\,'
C:\Users\DELL\AppData\Local\Temp\ipykernel_4276\3454143362.py:2: SyntaxWarning: invalid escape sequence '\,'
  punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
